Add files via upload

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -3818,14 +3818,14 @@ start() {
   echo "cat $Imagecommandscript | nl -ba >> $Dockerlogfile"
   echo ""
   
-  [ "$Initsystem" = "tini" ] && {
-    echo "docker info | grep 'Init Binary: docker-init' >/dev/null || {"
-    echo "  echo 'x11docker ERROR: Your docker installation does not have an init binary"
-    echo "  although option --init is listed in \"docker run --help\"."
-    echo "  This docker package issue is at least known for openSUSE."
-    echo "  Use x11docker option --no-init to avoid this error.'"
+ # [ "$Initsystem" = "tini" ] && {
+ #   echo "docker info | grep 'Init Binary: docker-init' >/dev/null || {"
+ #   echo "  echo 'x11docker ERROR: Your docker installation does not have an init binary"
+ #   echo "  although option --init is listed in \"docker run --help\"."
+ #   echo "  This docker package issue is at least known for openSUSE."
+ #   echo "  Use x11docker option --no-init to avoid this error.'"
  #   echo "  exit 1"
-    echo "}"
+ #   echo "}"
     echo ""
   }
 
